export type {
  WorkingHours,
  ScheduledSlot,
  SuggestedSlot,
  SlotProposal,
  GoogleCalendarEntry,
  GoogleAccountPublic,
  MicrosoftAccountPublic,
  AuthMeResponse,
  FreeQuotaSnapshot,
  BillingPlan,
  Entitlements,
  ActivityLogEntry,
  NotificationDeliveryMode,
  NotificationOutboundFrequency,
} from "./core";

export {
  login,
  fetchPendingTwoFactorMeta,
  sendEmailOtpForPendingLogin,
  verifyTwoFactor,
  totpSetup,
  totpEnable,
  totpDisable,
  totpCancelSetup,
  requestEmail2faEnrollment,
  confirmEmail2faEnrollment,
  putTotpEmailFallback,
  requestEmail2faDisableOtp,
  disableEmailOtp2fa,
  register,
  verifyEmailApi,
  resendVerificationApi,
  forgotPasswordApi,
  resetPasswordApi,
  getGoogleSsoUrl,
  getMicrosoftSsoUrl,
  shareInviteApi,
  getMe,
  createBillingPortalSession,
  updateProfile,
  logout,
  changePassword,
  getMyExport,
  deleteMyAccount,
  getMyActivity,
  globalSearch,
  lookupUser,
  lookupUserByUid,
} from "./auth";
export type { SearchResult, LoginOutcome, TwoFactorMethod } from "./auth";

export {
  getTodos,
  getAssignedTodos,
  getArchivedTodos,
  createTodo,
  updateTodo,
  deleteTodo,
  deleteArchivedTodoPermanently,
  purgeAllArchivedTodos,
  reorderTodos,
  exportTasksCsv,
  exportTasks,
  importTasks,
  previewTaskImport,
  confirmTaskImport,
  getTaskActivity,
  getComments,
  getCommentCounts,
  getAttachmentCounts,
  postCommentApi,
  editCommentApi,
  deleteCommentApi,
  toggleReactionApi,
  uploadAttachment,
  getAttachments,
  downloadAttachment,
  deleteAttachmentApi,
} from "./todos";
export type {
  Priority,
  Effort,
  TodoStatus,
  AssignmentStatus,
  RecurrenceFrequency,
  Recurrence,
  Todo,
  CreateTodoPayload,
  UpdateTodoPayload,
  Comment,
  CommentPostResult,
  Attachment,
  TaskImportPreviewResult,
} from "./todos";

export {
  getCollaborators,
  getEmailSuggestions,
  getReceivedInvitations,
  inviteCollaborator,
  resendCollaboratorInvite,
  removeCollaborator,
  acceptCollaboration,
  declineCollaboration,
  getTeams,
  createTeam,
  addTeamMember,
  removeTeamMemberApi,
  updateMemberRoleApi,
  getTeamDashboard,
  getTeamReporting,
  deleteTeamApi,
  getOwnedTeams,
  transferTeamOwnership,
  getTeamCollaborators,
  addTeamCollaboratorApi,
  removeTeamCollaboratorApi,
  getNotifications,
  getUnreadCount,
  markNotificationRead,
  markAllNotificationsRead,
} from "./teams";
export type {
  Collaborator,
  TeamCollaborator,
  TeamMemberRole,
  TeamMember,
  Team,
  ReceivedInvitation,
  TeamDashboardData,
  TeamReportingPeriodDays,
  TeamReportingMemberRow,
  TeamReportingProjectRow,
  TeamReportingVelocityWeek,
  TeamReportingSnapshot,
  TeamReportingResponse,
  NotificationType,
  AppNotification,
} from "./teams";

export {
  getProjects,
  getProject,
  getProjectAccess,
  putProjectAccess,
  createProject,
  updateProject,
  deleteProjectApi,
  reorderProjects,
  getProjectTodos,
  getAllProjectTodos,
  createPhase,
  updatePhaseApi,
  deletePhaseApi,
  convertPhaseToSubproject,
  convertSubprojectToPhase,
  uploadCsvPreview,
  confirmCsvImport,
  exportProjectData,
  importProjectTasksFile,
} from "./projects";
export type {
  ProjectStatus,
  ProjectPhase,
  Project,
  ProjectAccessRole,
  ProjectAccessEntry,
  ProjectAccessInfo,
  CreateProjectPayload,
  UpdateProjectPayload,
  CreatePhasePayload,
  UpdatePhasePayload,
  ConvertPhaseToSubprojectPayload,
  ImportParsedTask,
  ImportError,
  ImportPreview,
} from "./projects";

export type { SlotConflict, BookSlotResult } from "./calendar";
export {
  getTaskSlots,
  bookTaskSlot,
  clearTaskSlot,
  getCalendarEvents,
  getGoogleAuthUrl,
  disconnectGoogleCalendar,
  getAccountCalendars,
  saveAccountCalendars,
  disconnectGoogleAccount,
  getMicrosoftAuthUrl,
  disconnectMicrosoftCalendar,
  getMicrosoftAccountCalendars,
  saveMicrosoftAccountCalendars,
  disconnectMicrosoftAccount,
  getInAppScheduledSlotsPendingCount,
  syncInAppScheduledSlotsToCalendar,
  syncOneScheduledSlotToCalendar,
} from "./calendar";
export type {
  CalendarEvent,
  CalendarEventsResponse,
  InAppSlotsPendingCountResponse,
  SyncInAppScheduledSlotsResponse,
  SyncOneInAppScheduledSlotResponse,
} from "./calendar";

export {
  getNotes,
  getSharedNotes,
  getNotesByTodo,
  getTodoNoteMap,
  createNoteApi,
  updateNoteApi,
  deleteNoteApi,
  getArchivedNotes,
  restoreArchivedNoteApi,
  purgeArchivedNoteApi,
  syncNotesApi,
  exportNotesMarkdown,
  exportNotes,
  importNotesFile,
} from "./notes";
export type { Note } from "./notes";

export {
  getWebhooks,
  saveWebhook,
  deleteWebhookApi,
  testWebhookApi,
} from "./webhooks";
export type {
  WebhookEvent,
  WebhookPlatform,
  WebhookConfig,
} from "./webhooks";

export {
  getAdminStats,
  getAdminUsers,
  getAdminInvites,
  getAdminActivity,
  getAdminSessions,
  getAdminIntegrations,
  getAdminUserExport,
  deleteAdminUser,
  getAdminCompletionRates,
  postAdminUserBillingPortalSession,
  patchAdminUserBillingPlan,
  patchAdminUserEarlyBird,
  postAdminInviteRemind,
  deleteAdminInvite,
} from "./admin";
export type {
  AdminStats,
  AdminUser,
  AdminInviteLogEntry,
  InviteConversionStatus,
  InviteLogEntry,
  SessionInfo,
  IntegrationOverview,
  CompletionRate,
} from "./admin";

export { postPricingContact } from "./marketing";
export type { PostPricingContactBody, PostPricingContactResult } from "./marketing";
